### ISSUE TITLE
error when trying to use extension

### ISSUE THREAD

**Issue by ride5k** [muerrilla/stable-diffusion-Latentshop#2]
`Error running process: T:\auto1111\stable-diffusion-webui-directml\extensions\stable-diffusion-Latentshop\scripts\latentshop.py
Traceback (most recent call last):
  File "T:\auto1111\stable-diffusion-webui-directml\modules\scripts.py", line 451, in process
    script.process(p, *script_args)
  File "T:\auto1111\stable-diffusion-webui-directml\extensions\stable-diffusion-Latentshop\scripts\latentshop.py", line 209, in process
    grey_latent = self.make_grey_latent(p, z_brightness, z_r, z_g, z_b)
  File "T:\auto1111\stable-diffusion-webui-directml\extensions\stable-diffusion-Latentshop\scripts\latentshop.py", line 280, in make_grey_latent
    guide = p.sd_model.get_first_stage_encoding(p.sd_model.encode_first_stage(guide))
  File "T:\auto1111\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "T:\auto1111\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "T:\auto1111\stable-diffusion-webui-directml\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "T:\auto1111\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 830, in encode_first_stage
    return self.first_stage_model.encode(x)
  File "T:\auto1111\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\autoencoder.py", line 83, in encode
    h = self.encoder(x)
  File "T:\auto1111\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "T:\auto1111\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 523, in forward
    hs = [self.conv_in(x)]
  File "T:\auto1111\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "T:\auto1111\stable-diffusion-webui-directml\extensions-builtin\Lora\lora.py", line 411, in lora_Conv2d_forward
    return lora_forward(self, input, torch.nn.Conv2d_forward_before_lora)
  File "T:\auto1111\stable-diffusion-webui-directml\extensions-builtin\Lora\lora.py", line 366, in lora_forward
    return original_forward(module, input)
  File "T:\auto1111\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "T:\auto1111\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
  File "T:\auto1111\stable-diffusion-webui-directml\modules\dml\amp\autocast_mode.py", line 32, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: pre_forward(op, args, kwargs))
  File "T:\auto1111\stable-diffusion-webui-directml\modules\dml\amp\autocast_mode.py", line 9, in pre_forward
    return forward(*args, **kwargs)
RuntimeError: Input type (struct c10::Half) and bias type (float) should be the same`

**Comment by muerrilla** [comment]
Are you by any chance running sd-webui with the --no-half command line argument?

**Comment by muerrilla** [comment]
Are you by any chance running sd-webui with the --no-half command line argument?

**Comment by ride5k** [comment]
yes, was running with no-half
updated and running successfully!
thank you, having fun playing around
